services:
  db:
    image: postgres:16
    container_name: food-diary-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: food_diary_db
      POSTGRES_USER: food_diary_user
      POSTGRES_PASSWORD: food_diary_password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: food-diary-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://food_diary_user:food_diary_password@db:5432/food_diary_db
      ALLOWED_HOSTS: localhost,127.0.0.1
    expose:
      - "8000"
    volumes:
      - static_data:/app/staticfiles
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: food-diary-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_data:/static:ro
    depends_on:
      - backend

volumes:
  postgres_data:
  static_data: