version: "3.9"

services:
  db:
    image: postgres:16
    container_name: food-diary-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: food_diary_db
      POSTGRES_USER: food_diary_user
      POSTGRES_PASSWORD: food_diary_password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: