services:
  db:
    image: postgres:16
    container_name: food-diary-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: food_diary_db
      POSTGRES_USER: food_diary_user
      POSTGRES_PASSWORD: food_diary_password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: food-diary-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://food_diary_user:food_diary_password@db:5432/food_diary_db
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: